services:
  - type: web
    name: seekreap-production
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: npm install
    startCommand: node dashboard/server.js
