from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import httpx
import os
from datetime import datetime
from typing import Optional, Dict, Any, List
import uvicorn

app = FastAPI(title="SeekReap Tier-4 Orchestrator")

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Environment variables
TIER3_URL = os.getenv("TIER3_URL", "https://seekreap-tier-3-private.onrender.com")
PORT = int(os.getenv("PORT", 10000))

# Pydantic models
class Envelope(BaseModel):
    id: str
    timestamp: float
    payload: Dict[str, Any]
    schema_version: str
    orchestration_policy: str
    signature: str
    metadata: Dict[str, Any]

class BatchEnvelope(BaseModel):
    envelopes: List[Envelope]

# Health check endpoint
@app.get("/health")
async def health_check():
    """Health check endpoint for monitoring"""
    # Check connection to Tier-3
    tier3_status = "unknown"
    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(f"{TIER3_URL}/health", timeout=5.0)
            if response.status_code == 200:
                tier3_status = "healthy"
            else:
                tier3_status = "unhealthy"
    except:
        tier3_status = "unreachable"
    
    return {
        "status": "healthy",
        "tier": 4,
        "timestamp": datetime.now().isoformat(),
        "tier3_url": TIER3_URL,
        "tier3_status": tier3_status,
        "version": "2.0.0"
    }

# Process single envelope endpoint
@app.post("/process-envelope")
async def process_envelope(envelope: Envelope):
    """Process a single envelope by forwarding to Tier-3"""
    print(f"Tier-4 received envelope: {envelope.id}")
    print(f"Processing envelope: {envelope.id}")
    print(f"Policy: {envelope.orchestration_policy}")
    
    try:
        # Forward to Tier-3
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{TIER3_URL}/process-envelope",
                json=envelope.dict(),
                timeout=30.0
            )
            
            if response.status_code == 200:
                result = response.json()
                print(f"Tier-3 response: {result.get('decision', 'unknown')}")
                return result
            else:
                print(f"Tier-3 error: {response.status_code}")
                return {
                    "decision": "ERROR",
                    "confidence": 0,
                    "risk_factors": [f"Tier-3 returned {response.status_code}"],
                    "appeal_text": None,
                    "job_id": envelope.payload.get("job_id")
                }
    except Exception as e:
        print(f"Error forwarding to Tier-3: {str(e)}")
        return {
            "decision": "ERROR",
            "confidence": 0,
            "risk_factors": [f"Error: {str(e)}"],
            "appeal_text": None,
            "job_id": envelope.payload.get("job_id")
        }

# Process batch endpoint
@app.post("/process-batch")
async def process_batch(batch: BatchEnvelope):
    """Process multiple envelopes in batch"""
    print(f"Tier-4 received batch of {len(batch.envelopes)} envelopes")
    
    results = []
    for envelope in batch.envelopes:
        result = await process_envelope(envelope)
        results.append(result)
    
    return {"results": results}

# Test endpoint for creating test envelopes
@app.post("/test-envelope")
async def test_envelope(request: Request):
    """Create a test envelope for development"""
    data = await request.json()
    
    # Create a test envelope
    test_envelope = {
        "id": f"test-{datetime.now().timestamp()}",
        "timestamp": datetime.now().timestamp(),
        "payload": {
            "job_id": data.get("job_id", 999),
            "content_id": data.get("content_id", "test-content"),
            "creator_id": data.get("creator_id", 1),
            "job_type": data.get("job_type", "video"),
            "params": data.get("params", {})
        },
        "schema_version": "tier2-envelope-v1",
        "orchestration_policy": data.get("policy", "job_processing"),
        "signature": f"test-signature-{datetime.now().timestamp()}",
        "metadata": {
            "source": "tier4_test",
            "test": True
        }
    }
    
    # Process it
    return await process_envelope(Envelope(**test_envelope))

# Root endpoint
@app.get("/")
async def root():
    return {
        "status": "Tier-4 is running",
        "version": "2.0.0",
        "endpoints": [
            "/health",
            "/process-envelope",
            "/process-batch",
            "/test-envelope",
            "/docs",
            "/redoc"
        ]
    }

# OpenAPI docs endpoints are auto-generated by FastAPI

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=PORT)

# Add job endpoints that proxy to Tier-3
@app.get("/api/submissions")
async def get_submissions():
    """Get all jobs from Tier-3"""
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{TIER3_URL}/jobs")
        return response.json()

@app.get("/api/submissions/{job_id}")
async def get_submission(job_id: int):
    """Get specific job from Tier-3"""
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{TIER3_URL}/jobs/{job_id}")
        return response.json()

@app.post("/api/submit")
async def submit_job(request: Request):
    """Submit job to Tier-3"""
    data = await request.json()
    async with httpx.AsyncClient() as client:
        response = await client.post(f"{TIER3_URL}/jobs", json=data)
        return response.json()

# CORRECTED endpoints based on Tier-3 OpenAPI spec
@app.get("/api/submissions")
async def get_submissions():
    """Get all jobs from Tier-3 - Note: Tier-3 doesn't have a list endpoint!"""
    # Tier-3 doesn't have a list endpoint, so this will need special handling
    # You might need to maintain a local cache or redesign this
    return {"error": "Tier-3 doesn't support listing all jobs", "jobs": []}

@app.get("/api/submissions/{job_id}")
async def get_submission(job_id: int):
    """Get specific job from Tier-3 using their /api/job/{job_id} endpoint"""
    async with httpx.AsyncClient() as client:
        # Use the CORRECT path from Tier-3's OpenAPI spec
        response = await client.get(f"{TIER3_URL}/api/job/{job_id}")
        return response.json()

@app.post("/api/submit")
async def submit_job(request: Request):
    """Submit job to Tier-3"""
    data = await request.json()
    # Tier-3 likely expects this at a specific endpoint - check which one accepts POST
    # Based on OpenAPI, possible endpoints: /process-envelope or /api/process-submission
    async with httpx.AsyncClient() as client:
        # Try the process-envelope endpoint first
        response = await client.post(f"{TIER3_URL}/process-envelope", json={
            "id": f"job-{data.get('job_id', 'new')}",
            "timestamp": datetime.now().timestamp(),
            "payload": data,
            "schema_version": "1.0",
            "orchestration_policy": "standard",
            "signature": "tier4-signature"
        })
        return response.json()
